//constants.ts
export const FACULTIES = [
  'Faculty of Business',
  'Faculty of Engineering',
  'Faculty of Medicine',
  'Faculty of Science',
  'Faculty of Pharmacy',
  'Faculty of Computer and Information Sciences',
  'Faculty of Dentistry',
  'Faculty of Al-Alsun',
  'Faculty of Education',
  'Faculty of Law',
  'Faculty of Agriculture',
  'Faculty of Specific Education',
  'Faculty of Women',
  'Faculty of Arts',
  'Faculty of Nursing',
  'Faculty of Postgraduate Childhood Studies',
  'Faculty of Graduate Studies and Environment Research',
  'Faculty of Archaeology',
  'Faculty of Arid Land Agricultural Research Institute',
  'Faculty of Veterinary Medicine',
  'Faculty of Media and Mass Communication',
  'Other'
];
export const DEGREE_LEVEL_OPTIONS = [
  { value: 'undergraduate', label: 'Student' },
  { value: 'graduate', label: 'Graduate' },
];
export const ENUM_VALUES = {
  GENDER: ['male', 'female'] as const,
  DEGREE_LEVEL: ['undergraduate', 'graduate'] as const,
  CLASS_LEVEL: ['1', '2', '3', '4', '5'] as const,
  MARKETING_SOURCE: [
    'linkedin', 'facebook', 'instagram', 'friends',
    'banners_in_street', 'information_session_at_faculty',
    'campus_marketing', 'other'
  ] as const,
  USER_ROLE: [
    'admin', 'team_leader', 'registration', 'building',
    'attendee', 'volunteer', 'info_desk'
  ] as const
};


export const CLASS_YEARS = [
  { value: '1', label: '1st Year' },
  { value: '2', label: '2nd Year' },
  { value: '3', label: '3rd Year' },
  { value: '4', label: '4th Year' },
  { value: '5', label: '5th Year' }
];

export const HOW_DID_YOU_HEAR_OPTIONS = [
  { value: 'linkedin', label: 'LinkedIn' },
  { value: 'facebook', label: 'Facebook' },
  { value: 'instagram', label: 'Instagram' },
  { value: 'friends', label: 'Friends' },
  { value: 'banners_in_street', label: 'Banners in Street' },
  { value: 'information_session_at_faculty', label: 'Information Session at Faculty' },
  { value: 'campus_marketing', label: 'Campus Marketing' },
  { value: 'other', label: 'Other' }
];

export const UNIVERSITIES = [
  'Ain Shams University',
  'Other'
];

export const OTHER_UNIVERSITIES = [
  'Cairo University',
  'Alexandria University',
  'Assiut University',
  'Tanta University',
  'Mansoura University',
  'Zagazig University',
  'Helwan University',
  'Minya University',
  'Menoufia University',
  'Suez Canal University',
  'South Valley University',
  'Beni Suef University',
  'Fayoum University',
  'Benha University',
  'Kafr El-Sheikh University',
  'Sohag University',
  'Port Said University',
  'Damanhour University',
  'Aswan University',
  'Damietta University',
  'Suez University',
  'Sadat City University',
  'Arish University',
  'New Valley University',
  'Matrouh University',
  'Luxor University',
  'Al-Azhar University',
  '6th of October University',
  'October University for Modern Sciences and Arts (MSA)',
  'Misr University for Science and Technology',
  'Misr International University',
  'German University in Cairo',
  'Ahram Canadian University',
  'British University in Egypt',
  'Modern University for Technology and Information',
  'Sinai University',
  'Pharos University in Alexandria',
  'Nahda University in Beni Suef',
  'Future University in Egypt',
  'Egyptian Russian University',
  'Delta University for Science and Technology',
  'Heliopolis University',
  'New Giza University',
  'Deraya University',
  'Badr University in Cairo',
  'Horus University',
  'Egyptian Chinese University',
  'Merit University',
  'Sphinx University',
  'Al Salam University',
  'Badr University in Assiut',
  'New Salhia University',
  'Al Hayat University',
  'May University in Cairo',
  'Al Riyada University for Science and Technology',
  'Innovation University',
  'City University in Cairo',
  'El Sewedy University for Technology',
  'Rashid University',
  'King Salman International University',
  'Alamein International University',
  'Galala University',
  'New Mansoura University',
  'Egyptian E-Learning Private University',
  'Nile University',
  'French University in Egypt',
  'Egypt University of Informatics',
  'Helwan National University',
  'Mansoura National University',
  'Benha National University',
  'Menoufia National University',
  'Beni Suef National University',
  'Assiut National University',
  'South Valley National University',
  'Minya National University',
  'East Port Said National University',
  'Alexandria National University',
  'Zagazig National University',
  'New Ismailia National University',
  'Zewail City of Science and Technology',
  'American University in Cairo',
  'Egypt-Japan University of Science and Technology',
  'German International University',
  'ESLSCA University',
  'German University of Berlin (El Gouna)',
  'Senghor University',
  'Arab Academy for Science, Technology and Maritime Transport',
  'Arab Open University',
  'New Cairo Technological University',
  'Delta Technological University',
  'Beni Suef Technological University',
  'New Assiut Technological University',
  'Borg El Arab Technological University',
  'East Port Said Technological University',
  '6th of October Technological University',
  'Assiut Technological University',
  'Samannoud Technological University',
  'Tiba Technological University',
  'Helwan Technological University',
  'Fayoum Technological University'
];